---

# Command line vars (-e varname=true|false)
#
# **Required** - Name of the service to deploy/restart.  Must be one of `mrt_services`
service_name: ''
#
# Unless this is set to true (-e exec=true) all actions run in no-op mode
exec: false
#
# Set this to false to prevent puppet runs
run_puppet: true
#
# Set this to true (-e deploy=true) to enable service deployment tasks
deploy: false
#
# Set this to false to prevent service restarts
restart: true

# These can be set in host_vars to disable actions on specific hosts.
# See `../host_vars/notes`
#
do_not_deploy: false
do_not_restart: false
do_not_deregister: false


availability_zones:
- us-west-2a
- us-west-2b
- us-west-2c
puppet_user: uc3puppet
mrt_services:
- mrt-access
- mrt-audit
- mrt-ingest
- mrt-inventory
- mrt-replic
- mrt-store
- ldap
- puma
service_user:
  mrt-access: dpr2store
  mrt-audit: dpr2
  mrt-ingest: dpr2
  mrt-inventory: dpr2
  mrt-replic: dpr2
  mrt-store: dpr2store
build_content_url:
  mrt-access: http://localhost:35121/static/build.content.txt
  mrt-audit: http://localhost:37001/mrtaudit/static/build.content.txt
  mrt-ingest: http://localhost:33121/static/build.content.txt
  mrt-inventory: http://localhost:36121/mrtinv/static/build.content.txt
  mrt-replic: http://localhost:38001/mrtreplic/static/build.content.txt
  mrt-store: http://localhost:35121/static/build.content.txt
  
cdlsysctl: /usr/local/bin/cdlsysctl
puppet_apply_script: /apps/uc3puppet/bin/uc3_pupapply.sh
cap_deploy_script: /{{ service_user[service_name] }}/bin/cap_deploy.sh
