---

- when: ansible_ec2_placement_availability_zone == az
  block:

  - name: "Handle ALB target de-registration - {{ az }}"
    include_tasks: roles/mrt_service_restart/tasks/deregister_elb_target.yaml

  - name: "Restart service - {{ az }}"
    include_tasks: roles/mrt_service_restart/tasks/restart_mrt_service.yaml

  - name: "Handle ALB target re-registration - {{ az }}"
    include_tasks: roles/mrt_service_restart/tasks/reregister_elb_target.yaml
    when: exec and not do_not_deregister
