---

- name: "Check for Capisrano deploy script - {{ az }}"
  ansible.builtin.stat:
    path: "{{ cap_deploy_script }}"
  register: script_status

- name: "Query configured service release"
  become: true
  become_method: sudo
  become_user: "{{ service_user[service_name] }}"
  ansible.builtin.command: "grep 'MERRITT_SERVICE_RELEASE=' {{ cap_deploy_script }}"
  register: configured

- name: "Query deployed build tag"
  ansible.builtin.uri:
    url: "{{ build_content_url[service_name] }}"
    return_content: true
  register: deployed

- name: "set facts 'configured_rev' and 'deployed_rev'"
  ansible.builtin.set_fact:
    configured_rev: "{{ configured.stdout_lines[0].split('=')[-1] }}"
    deployed_rev: "{{ deployed.content.split()[-1] }}"

- name: "Test if configured service release is already deployed"
  ansible.builtin.set_fact:
    already_deployed: "{{ ansible_facts.configured_rev == ansible_facts.deployed_rev }}"

- name: "Report configured vs. deployed"
  debug:
    msg: |
      "configured_rev: {{ configured_rev }}"
      "deployed_rev: {{ deployed_rev }}"
      "already_deployed: {{ already_deployed }}"

- when: exec|bool and script_status.stat.executable is defined and script_status.stat.executable and not already_deployed
  block:

  - name: "run cap deploy - {{ az }}"
    become: true
    become_method: sudo
    become_user: "{{ service_user[service_name] }}"
    ansible.builtin.command: "{{ cap_deploy_script }}"
    register: result

  - name: "Report cap deploy success - {{ az }}"
    debug:
      msg: "{{ result.stdout_lines }}"
    when: not result.failed
  
  - name: "Report cap deploy failure - {{ az }}"
    debug:
      msg: "{{ result.stderr_lines }}"
    when: result.failed
    failed_when: true
