---

- name: Validate user provided 'service_name' variable  
  debug:
    msg: "FAIL! service_name '{{ service_name }}' is invalid. Must be one of {{ mrt_services }}."
  when: mrt_services is not ansible.builtin.contains(service_name)
  failed_when: true

- when: deploy|bool
  block:
  - name: "If running a deploy, validate 'service_name' is a tomcat service"
    debug:
      msg: "FAIL! service_name '{{ service_name }}' is not a tomcat service. Must be one of {{ tomcat_services }}."
    when: tomcat_services is not ansible.builtin.contains(service_name)
    failed_when: true

- name: Validate service is enabled in systemd
  ansible.builtin.command: "systemctl is-enabled {{ service_name }}"
  ignore_errors: true
  register: result

- when: result.failed
  debug:
    msg: "FAIL! service_name '{{ service_name }}' is not enabled in systemd"
  failed_when: true


- when: not do_not_restart
  block:

  - name: Get EC2 Metadata
    amazon.aws.ec2_metadata_facts:

  - name: Get initial list of target groups
    delegate_to: localhost
    community.aws.elb_target_info:
      instance_id: "{{ ansible_ec2_instance_id }}"
      region: "{{ ansible_ec2_placement_region }}"
      aws_config:
        retries:
          total_max_attempts: 10
          mode: adaptive
    register: target_info
  
  - name: save fact for later
    ansible.builtin.set_fact:
      original_tgs: "{{ target_info.instance_target_groups }}"

  - name: Run control task for each AZ
    include_tasks: roles/mrt_service_restart/tasks/control.yaml
    loop: "{{ availability_zones }}"
    loop_control:
      loop_var: az
