---

#
# Validate user provided 'service_name' variable
#

- name: Validate user provided 'service_name' variable  
  debug:
    msg: "FAIL! service_name '{{ service_name }}' is invalid. Must be one of {{ mrt_services }}."
  when: mrt_services is not ansible.builtin.contains(service_name)
  failed_when: true

- name: Validate service is enabled in systemd
  ansible.builtin.command: "systemctl is-enabled {{ service_name }}"
  ignore_errors: true
  register: result

- when: result.failed
  debug:
    msg: "FAIL! service_name '{{ service_name }}' is not enabled in systemd"
  failed_when: true


- when: not do_not_restart
  block:

  - name: Get EC2 Metadata
    amazon.aws.ec2_metadata_facts:
  
  - name: Run control task for each AZ
    include_tasks: roles/mrt_service_restart/tasks/control.yaml
    loop: "{{ availability_zones }}"
    loop_control:
      loop_var: az
