---

- name: "Validate cdlsysctl script - {{ az }}"
  ansible.builtin.stat:
    path: "{{ cdlsysctl }}"
  register: script_status

- when: script_status.stat.executable is defined and script_status.stat.executable
  block:

  - when: exec|bool and not do_not_restart
    block:

    - name: "Run cdlsysctl restart - {{ az }}"
      ansible.builtin.command: "sudo {{ cdlsysctl }} restart {{ service_name }}"
      register: result
      ignore_errors: true
    
    - name: "Report restart failure - {{ az }}"
      debug:
        msg: "{{ result.stderr_lines }}"
      when: result.failed
      failed_when: true
  
  - name: "Run cdlsysctl status - {{ az }}"
    ansible.builtin.command: "{{ cdlsysctl }} status {{ service_name }}"
    register: result
  
  - name: "Report service status - {{ az }}"
    debug:
      msg: "{{ result.stdout_lines }}"
    when: result.stdout_lines is defined

  - name: "Query build tag - {{ az }}"
    ansible.builtin.uri:
      url: "{{ build_content_url[service_name] }}"
      return_content: true
    register: response
    #failed_when: response is failed or "'Build tag' not in response.content"

  - name: "Report build tag - {{ az }}"
    debug:
      msg: "{{ response.content }}"
    when: response.content is defined

